
services:
  
   mysql_db:
    container_name: mysql_db_container
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demo@123
    networks:
      - mywpnetwork
    volumes:
      - db_vol: /var/lib/mysql
        
   web_service:
    container_name: wp_container
      #depends on:
      # mysql_db:
    image: wordpress:latest
    restart: always
    ports:
      - "4000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db
      WORDPRESS_DB_USER: demouser
      WORDPRESS_DB_PASSWORD: demo@123
      WORDPRESS_DB_NAME: wordpress
    networks:
      - mywpnetwork
   
networks:
  mywpnetwork:

volumes:
  db_vol:

